# Generated by Django 4.2.1 on 2023-05-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_options_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='ratind',
            new_name='rating',
        ),
    ]
